name: Deploy
run-name: ${{ github.actor }} is deploying... 🚀
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pwd
